
spring:
  profiles:
    group:
      local: common, local
      dev: common, dev
      prod: common, prod
    active: ${spring.profiles.active}

---
spring:
  config:
    activate:
      on-profile: "common"

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.pw}
            redirect-uri: ${kakao.redirect.uri}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

constant:
  jwt:
    secret-key: ${jwt.secret.key}
    access-token-expiration-time: 43200000
    refresh-token-expiration-time: 604800000

server:
  forward-headers-strategy: FRAMEWORK

---
spring:
  config:
    activate:
      on-profile: "local"

  sql:
    init:
      platform: mysql
  datasource:
    url: ${LOCAL_DATABASE_URL}
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

---
spring:
  config:
    activate:
      on-profile: "dev"

  sql:
    init:
      platform: mysql
  datasource:
    url: ${DEV_DATABASE_URL}
    username: ${DEV_DATABASE_USERNAME}
    password: ${DEV_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

---
spring:
  config:
    activate:
      on-profile: "prod"

  sql:
    init:
      platform: mysql
  datasource:
    url: ${prod.database.url}
    username: ${prod.database.username}
    password: ${prod.database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false