spring:
  profiles:
    group: # Run - Edit Configurations - Active Profiles에서 설정
      local: common, local
      dev: common, dev
      prod: common, prod

---
spring:
  config:
    activate:
      on-profile: "common"

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLINET_ID}
            client-secret: ${KAKAO_CLIENT_PW}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

constant:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration-time: 43200000    # 12시간
    refresh-token-expiration-time: 604800000   # 7일

---
spring:
  config:
    activate:
      on-profile: "local"

